from copy import deepcopy
import re
from typing import Union, Optional, Iterator, Literal

from riggery.core.lib.serialize import simplify
from riggery.general.functions import short
from riggery.internal.typeutil import UNDEFINED
import riggery.core.lib.skel as _sk
from riggery.core.lib import names as _nm
from riggery.core.lib import meshutil as _mu

from ..nodetypes import __pool__ as nodes
from ..datatypes import __pool__ as data

import maya.cmds as m
import maya.api.OpenMaya as om


class Joint(nodes['Transform']):

    #------------------------------------------|    Constructor(s)

    @classmethod
    @short(name='n',
           matrix='m',
           rotateOrder='ro',
           parent='p',
           worldSpace='ws',
           freezeRotate='fr',
           displayLocalAxis='dla')
    def create(cls, *,
               name:Optional[str]=None,
               matrix=None,
               rotateOrder:Union[int, str]=0,
               parent=None,
               worldSpace:bool=False,
               freezeRotate:bool=True,
               displayLocalAxis:bool=True):
        """
        :param name/n: if omitted, defaults to Name blocks
        :param matrix/m: the initial node matrix; defaults to identity
        :param parent/p: a destination parent; defaults to None
        :param rotateOrder/ro: the initial rotate order; defaults to 'xyz'
        :param displayLocalAxis/dla: display the local transformation axes;
            defaults to True
        :param freezeRotate/fr: zero-out rotation (but keep joint orient);
            defaults to True
        :param worldSpace/ws: apply *matrix* in world-space; defaults to
            False
        :return: The transform node.
        """
        node = super().create(name=name,
                              matrix=matrix,
                              rotateOrder=rotateOrder,
                              parent=parent,
                              worldSpace=worldSpace,
                              displayLocalAxis=displayLocalAxis)

        if freezeRotate:
            node.makeIdentity(rotate=True, apply=True, jointOrient=False)

        return node

    #------------------------------------------|    DAG

    def findRootJoint(self):
        """
        Note that this may return ``self``.
        """
        lastVisited = None
        for parent in self.parents:
            if isinstance(parent, Joint):
                lastVisited = parent
                continue
            return self if lastVisited is None else lastVisited

    #------------------------------------------|    Constraints

    def attachWithoutSkew(self, slave, decompose=False):
        # This works, but too many damn steps

        slave = nodes['DagNode'](slave)
        iniPose = slave.getMatrix(worldSpace=True)

        tmtx = (slave.worldPosition()
                ^ self.attr('wm').asOffset()).asTranslateMatrix()
        rmtx = self.attr('wm').pick(r=True)

        smtx = self.attr('inverseScale').asScaleMatrix(
        ).inverse() * self.attr('pm')[0].pick(s=True)

        mtx = smtx * rmtx * tmtx

        if decompose:
            mtx.decomposeAndApply(slave, mo=True, ws=True)

        else:
            mtx.applyViaOpm(slave, mo=True, ws=True)

        return self

    #------------------------------------------|    Skel

    def chainFromHere(self) -> '_sk.Chain':
        """
        :return: A chain from this joint to the tip joint or the first branch.
        """
        return _sk.Chain.fromStart(self)

    def chainTo(self, endJoint) -> '_sk.Chain':
        """:return: A chain from this joint to *endJoint*, inclusively."""
        return _sk.Chain.fromStartEnd(self, endJoint)

    def boneFromHere(self) -> '_sk.Chain':
        """
        :raises RuntimeError: More than one child joint.
        :return: A chain from this joint to its child, inclusively.
        """
        children = list(self.iterChildren(type='joint'))

        if len(children) == 1:
            return _sk.Chain([self, children[0]])

        raise RuntimeError('no unambiguous joint child')

    def bonesFromHere(self) -> Iterator['_sk.Chain']:
        """
        Yields all possible bones (two-joint
        :meth:`~riggery.core.lib.skel.Chain` instances) from this joint
        downwards. Iteration will terminate at junctions.
        """
        yield from _sk.iterBonesFrom(self)

    #------------------------------------------|    Joint labels

    def getLabelState(self) -> dict:
        """:return: Label information in a dict macro."""

        out = {'side': self.attr('side').get(),
               'type': self.attr('type').get()}

        out['otherType'] = self.attr('otherType').get()

        if not out['otherType']:
            out['otherType'] = ''

        return out

    def setLabelState(self, macro:dict):
        """
        :param dict macro: a macro generated by :meth:`getLabelState`.
        :return: self
        """
        for k, v in macro.items():
            self.attr(k).set(v)
        return self

    def resetLabel(self):
        """
        Resets joint labelling.
        :return: self
        """
        self.setLabelState({'otherType':'', 'side':0, 'type':0})
        return self

    def autoLabel(self) -> dict:
        """
        Only works if the joint name starts with 'L_' or 'R_'.
        Uses the side prefix to configure the 'side' label, and
        the remainder to configure the 'otherType' field.

        :return: A macro for the current, unmodified state, for later
            restoration if needed.
        """
        state = self.getLabelState()
        self.resetLabel()

        n = str(self).split('|')[-1]
        pat = r"^([LR])_(.*)$"
        mt = re.match(pat, n)

        if mt:
            side, desc = mt.groups()
            self.setLabelState({'side': {'L':'Left', 'R':'Right'}[side],
                                'type': 'Other',
                                'otherType': desc})

        return state

    #------------------------------------------|    Orientation

    def reset(self):
        """
        Sets this joint's rotations to (0, 0, 0) and its scale to (1, 1, 1).
        Translation is not edited.
        """
        self.attr('r').set((0, 0, 0))
        self.attr('s').set((1, 1, 1))
        return self

    @short(worldSpace='ws')
    def getRestRotateMatrix(self, worldSpace:bool=False):
        """
        Returns the rotation matrix at which this joint's rotation will be zero.
        """
        mtx = self.attr('jo')().asMatrix()

        if worldSpace:
            mtx *= self.attr('pm')[0]()
            mtx = mtx.pick(r=True)

        return mtx

    @short(worldSpace='ws',
           preserveChildren='pc',
           resetRotation='rr')
    def setRestRotateMatrix(self,
                            matrix,
                            worldSpace:bool=False,
                            resetRotation:bool=False,
                            preserveChildren:bool=True):
        """
        Sets the rotation matrix at which this joint's rotations will be zero.

        :param matrix: the matrix to use
        :param worldSpace/ws: specifies that *matrix* is in world-space;
            defaults to False
        :param resetRotation/rr: if this is True, the joint will be zeroed at
            its current pose; otherwise, the joint will maintain its pose, and
            its rotations must be zeroed later to reach *matrix*; defaults to
            False
        :param preserveChildren/pc: preserve child world-space transformations;
            defaults to True
        """
        # Resolve matrix
        joMatrix = data.Matrix(matrix)

        if worldSpace:
            joMatrix *= self.attr('pim')[0]()

        # Gather child info
        if preserveChildren:
            childStates = [(child, child.getMatrix(ws=True))
                           for child in self.iterChildren(type='transform')]

        if not resetRotation:
            pose = self.getMatrix()

        # Apply matrix
        joEuler = joMatrix.decompose()['rotate']
        self.attr('jointOrient').set(joEuler)

        if resetRotation:
            self.attr('r').set((0, 0, 0))
        else:
            self.setMatrix(pose)

        if preserveChildren:
            for child, childPose in childStates:
                child.setMatrix(childPose, ws=True)

        return self

    @short(worldSpace='ws', freeze='fr')
    def setJointOrientMatrix(self,
                             matrix,
                             worldSpace:bool=False,
                             freeze:bool=True):
        """
        Sets the joint orient matrix for this joint. If *freeze* is True (the
        default), local rotations will be zeroed. Otherwise, they will be edited
        to compensate. In either case, the pose will be preserved.

        :param matrix: the matrix to use
        :param worldSpace/ws: indicates that *matrix* is a world-space matrix;
            defaults to False
        :param freeze/fr: freeze local rotations; defaults to True
        """
        joMatrix = data.Matrix(matrix)

        if worldSpace:
            joMatrix *= self.attr('pim')[0]()

        joMatrix = joMatrix.pick(r=True)

        pose = self.getMatrix().pick(r=True)

        rMatrix = self.attr('r')().asMatrix()
        joMatrix = rMatrix.inverse() * joMatrix

        self.attr('jointOrient').set(joMatrix.decompose()['rotate'])

        pose.decomposeAndApply(self, r=True)

        if freeze:
            self.makeIdentity(r=True, apply=True, jo=False)

        return self

    #------------------------------------------|    Skin clusters

    def iterSkinClusters(self) -> Iterator['nodes.SkinCluster']:
        return self.attr('worldMatrix')[0].iterOutputs(type='skinCluster')

    skinClusters = property(iterSkinClusters)

    #------------------------------------------|    Weights

    def iterVertsByDisk(self,
                        mesh:Union[str, 'nodes.DagNode'],
                        axis:Literal['x', 'y', 'z', '-x', '-y', '-z'],
                        diskRadius:float,
                        diskThickness:float,
                        firstHit:bool=False,
                        centered:bool=True) -> Iterator[str]:
        """
        Yields vertices on *mesh* that fall within a 'coin'-like disk projected
        from this joint.

        :param mesh: the mesh from which to yield vertices
        :param axis: the joint axis to use; one of 'x', 'y', 'z', '-x', '-y' or
            '-z'
        :param diskRadius: the disk radius
        :param diskThickness: the disk height
        :param firstHit: exclude re-entrant areas, e.g. an elbow that's further
            out from already-captured trunk vertices; defaults to False
        """
        jointMatrix = self.getMatrix(ws=True)
        diskCenter = jointMatrix.w
        diskVector = jointMatrix.getAxis(axis).normal() * diskThickness

        if centered:
            cylinderBase = diskCenter - diskVector * 0.5
        else:
            cylinderBase = diskCenter

        _mesh = str(mesh)

        for i in _mu.selectVertsInsideCylinder(_mesh,
                                               om.MPoint(cylinderBase),
                                               om.MVector(diskVector),
                                               diskRadius,
                                               firstHit=firstHit):
            yield f"{_mesh}.vtx[{i}]"

    #------------------------------------------|    Serialization

    def macro(self) -> dict:
        out = {'name': self.shortName(),
               'attrStates': {x: self.attr(x).getState() for x in (
                   't', 'r', 's', 'shear',
                   'offsetParentMatrix',
                   'rotateOrder',
                   'jointOrient',
                   'rotateAxis',
                   'radius',
                   'side',
                   'preferredAngle',
                   'stiffness',
                   'segmentScaleCompensate',
                   'type',
                   'otherType',
                   'drawLabel',
                   'displayLocalAxis',
                   'displayHandle',
                   'drawStyle',
                   'jointTypeX',
                   'jointTypeY',
                   'jointTypeZ'
               )}}
        parent = self.parent

        if parent:
            out['parent'] = parent.shortName()

        return out

    @classmethod
    @short(restoreInputs='ri',
           restoreValues='rv',
           restoreParent='rp',
           parent='p')
    def createFromMacro(cls,
                        macro:dict,
                        parent=UNDEFINED,
                        restoreInputs:bool=False,
                        restoreValues:bool=True,
                        restoreParent:bool=False):
        """
        :param parent/p: an optional override for the destination parent
        :param restoreParent/rp: ignored if *parent* has been provided; restore
            the parent embedded in the macro; defaults to False
        """
        kwargs = {}

        if not _nm.Name.__elems__:
            kwargs['name'] = macro['name']

        joint = Joint(m.createNode('joint', **kwargs))

        if parent is not UNDEFINED:
            joint.parent = parent
        elif restoreParent:
            parent = macro.get('parent')
            if parent:
                matches = m.ls(parent, type='transform')

                if len(matches) > 0:
                    joint.parent = matches[0]

        for x, state in macro['attrStates'].items():
            joint.attr(x).setState(state,
                                   input=restoreInputs,
                                   value=restoreValues)

        return joint