"""Utilities for skin weight wrangling."""

from itertools import chain
from typing import Union, Optional

import maya.cmds as m
import maya.api.OpenMaya as om
import maya.api.OpenMayaAnim as oma
from ...internal import str2api as _s2a, api2str as _a2s


class SkinClusterWeightsWrangler:

    #-------------------------------------|    Init

    def __init__(self, skin:str):
        self._skin = skin
        self._skinMObject = None
        self._skinMFn = None
        self._shapeDagPath = None
        self._numInfls = None
        self._shapeDependNode = None
        self._components = None

    #-------------------------------------|    Properties

    @property
    def numInfls(self) -> int:
        if self._numInfls is None:
            influence = m.skinCluster(self._skin, q=True, influence=True)
            if influence:
                self._numInfls = len(influence)
            else:
                self._numInfls = 0
        return self._numInfls

    @property
    def skinMObject(self) -> om.MObject:
        if self._skinMObject is None:
            self._skinMObject = _s2a.getNodeMObject(self._skin)
        return self._skinMObject

    @property
    def skinMFn(self) -> om.MFnBase:
        if self._skinMFn is None:
            self._skinMFn = oma.MFnSkinCluster(self.skinMObject)
        return self._skinMFn

    @property
    def components(self):
        if self._components is None:
            try:
                deformerSet = om.MFnSet(self.skinMFn.deformerSet)
            except:
                deformerSet = None

            if deformerSet is None:
                shapeName = _a2s.fromNodeMDagPath(self.shapeDagPath)
                shapeOutAttrStr = m.deformableShape(shapeName,
                                                    localShapeOutAttr=True)[0]
                shapeDependNode = self.shapeDependNode
                shapeMFn = om.MFnDependencyNode(shapeDependNode)
                outAttrMPlug = shapeMFn.findPlug(shapeOutAttrStr, False)
                outAttrMObj = outAttrMPlug.asMObject()

                geoDataFn = om.MFnGeometryData(outAttrMObj)
                self._components = geoDataFn.resolveComponentTagExpression('*')
            else:
                selectionList = deformerSet.getMembers(False)
                self._components = selectionList.getComponent(0)[1]

        return self._components

    @property
    def shapeDagPath(self):
        if self._shapeDagPath is None:
            shape = m.skinCluster(self._skin, q=True, geometry=True)[0]
            self._shapeDagPath = _s2a.getMDagPath(shape)
        return self._shapeDagPath

    @property
    def shapeDependNode(self):
        if self._shapeDependNode is None:
            sel = om.MSelectionList()
            sel.add(self.shapeDagPath)
            self._shapeDependNode = sel.getDependNode(0)
        return self._shapeDependNode

    def _getRawWeights(self) -> tuple[om.MDoubleArray, int]: # weights, numInfls
        return self.skinMFn.getWeights(self.shapeDagPath, self.components)

    def _rawWeightsToGroupedList(self, rawWeights, numInfls):
        out = [[]]

        for weight in rawWeights:
            pool = out[-1]
            pool.append(weight)

            if len(pool) == numInfls:
                out.append([])

        return out

    def getWeights(self) -> list[list[float]]:
        """
        Returns a list of lists (one for every component). Each sublist contains
        the weights for the influences for that component.
        """
        rawWeights, numInfls = self._getRawWeights()
        out = self._rawWeightsToGroupedList(rawWeights, numInfls)

        if len(out[-1]) == 0:
            del(out[-1])

        return out

    def _groupedListToRawWeights(self, groupedList):
        return om.MDoubleArray(list(chain.from_iterable(groupedList)))

    def setWeights(self, weights:list[list[float]]):
        """
        Sets the weights using the type of list generated by :meth:`getWeights`.
        """
        previousSetting = m.skinCluster(self._skin, q=True, nw=True)

        if previousSetting == 1:
            m.skinCluster(self._skin, e=True, nw=0)

        inflIndices = om.MIntArray(list(range(self.numInfls)))

        self.skinMFn.setWeights(self.shapeDagPath,
                                self.components,
                                inflIndices,
                                self._groupedListToRawWeights(weights),
                                False)

        if previousSetting == 1:
            m.skinCluster(self._skin, e=True, fnw=True)
            m.skinCluster(self._skin, e=True, nw=1)